application: word-cloud-1347
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: MySQLdb
  version: "latest"


handlers:
- url: /static/
  static_dir: static

- url: /.*
  script: wsgi.application